### ISSUE TITLE
[FF v3.23] Strange issue flashing on SFRC922D with dfu-util 0.10 (libusb 1.0.23) on Linux

### ISSUE THREAD

**Issue by Drag0nFly** [keirf/FlashFloppy#462]
I'm having no luck getting the FlashFloppy firmware to "stick" on this Gotek board. The board is a standard SFRC922D, and appears to be fresh from the factory (with whatever software it came preinstalled with).

Hooked it up to one of my A500 machines (which also has been tested with a different Gotek), and the only activity is the green LED (nothing on either LED or OLED display). No response to buttons, and no activity on USB stick (which also has been tested separately.)

I've run several (around 10) – apparently successful – firmware flashes using dfu-util (see output below). But it does not appear to actually get FlashFloppy on it (is there a way to *check* the .dfu file against what is actually written on the Gotek, btw.?)

Leaving a comment here out of desperation in case there is something I overlooked, as the wiki and several searches did not reveal a similar issue. Obviously there could be some kind of defect with this Gotek board (which would be a first as I have several)

Thanks for any input.

First step, removing the protection (if any)

```
sudo dfu-util -a 0 -s :unprotect:force -D /data/amiga/flashfloppy-v3.23/FF_Gotek-v3.23.dfu
dfu-util 0.10

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2020 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Match vendor ID from file: 0483
Match product ID from file: df11
Deducing device DFU version from functional descriptor length
Opening DFU capable USB device...
ID 0483:df11
Run-time device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuERROR, status = 10
dfuERROR, clearing status
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 2048
DfuSe interface name: "Internal Flash  "
Device disconnects, erases flash and resets now

```

Listing the device after it resets.

```
sudo dfu-util -l
dfu-util 0.10

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2020 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Deducing device DFU version from functional descriptor length
Found Runtime: [21ee:1100] ver=0391, devnum=9, cfg=1, intf=3, path="3-1.5.4.1", alt=0, name="UNKNOWN", serial="0009DD402B65"
```

Actually flashing the firmware (one of many identical tries)

```
sudo dfu-util -a 0 -D /data/amiga/flashfloppy-v3.23/FF_Gotek-v3.23.dfu
dfu-util 0.10

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2020 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Match vendor ID from file: 0483
Match product ID from file: df11
Deducing device DFU version from functional descriptor length
Opening DFU capable USB device...
ID 0483:df11
Run-time device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuERROR, status = 10
dfuERROR, clearing status
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 2048
DfuSe interface name: "Internal Flash  "
file contains 1 DFU images
Please note that the next version of dfu-util will automatically
set alternate interfaces based on the DfuSe file images!
parsing DFU image 1
Target name: ST...
image for alternate setting 0, (2 elements, total size = 112612)
parsing element 1, address = 0x08000000, size = 30328
Erase   	[=========================] 100%        30328 bytes
Erase    done.
Download	[=========================] 100%        30328 bytes
Download done.
parsing element 2, address = 0x08008000, size = 82268
Erase   	[=========================] 100%        82268 bytes
Erase    done.
Download	[=========================] 100%        82268 bytes
Download done.
Done parsing DfuSe file
```

Listing the device again

```
sudo dfu-util -l
dfu-util 0.10

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2020 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Deducing device DFU version from functional descriptor length
Found DFU: [0483:df11] ver=2200, devnum=43, cfg=1, intf=0, path="3-1.1", alt=1, name="@Option Bytes  /0x1FFFF800/01*016 e", serial="STM32"
Found DFU: [0483:df11] ver=2200, devnum=43, cfg=1, intf=0, path="3-1.1", alt=0, name="@Internal Flash  /0x08000000/128*002Kg", serial="STM32"
Found Runtime: [21ee:1100] ver=0391, devnum=9, cfg=1, intf=3, path="3-1.5.4.1", alt=0, name="UNKNOWN", serial="0009DD402B65"
```

Device is detected as follows:

```
[Sun May  2 19:22:19 2021] usb 3-1.1: Product: STM32 0x418 DFU Bootloade
[Sun May  2 19:22:19 2021] usb 3-1.1: Manufacturer: STMicroelectronics
[Sun May  2 19:22:19 2021] usb 3-1.1: SerialNumber: STM32
[Sun May  2 19:22:46 2021] usb 3-1.1: USB disconnect, device number 42
[Sun May  2 19:23:16 2021] usb 3-1.1: new full-speed USB device number 43 using ehci-pci
[Sun May  2 19:23:16 2021] usb 3-1.1: New USB device found, idVendor=0483, idProduct=df11, bcdDevice=22.00
[Sun May  2 19:23:16 2021] usb 3-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[Sun May  2 19:23:16 2021] usb 3-1.1: Product: STM32 0x418 DFU Bootloade
[Sun May  2 19:23:16 2021] usb 3-1.1: Manufacturer: STMicroelectronics
[Sun May  2 19:23:16 2021] usb 3-1.1: SerialNumber: STM32
```

The Gotek has a hard time being detected after unplugging and re-plugging it. I have however seen this on other Gotek boards (although those were flashed on W*n, as there was no dfu-util option back then.)

```
[Sun May  2 19:30:17 2021] usb 3-1.1: device descriptor read/64, error -32
[Sun May  2 19:30:17 2021] usb 3-1.1: new full-speed USB device number 48 using ehci-pci
[Sun May  2 19:30:17 2021] usb 3-1.1: device descriptor read/64, error -32
[Sun May  2 19:30:18 2021] usb 3-1.1: device descriptor read/64, error -32
[Sun May  2 19:30:18 2021] usb 3-1-port1: attempt power cycle
[Sun May  2 19:30:18 2021] usb 3-1.1: new full-speed USB device number 49 using ehci-pci
[Sun May  2 19:30:19 2021] usb 3-1.1: device not accepting address 49, error -32
[Sun May  2 19:30:19 2021] usb 3-1.1: new full-speed USB device number 50 using ehci-pci
[Sun May  2 19:30:19 2021] usb 3-1.1: device not accepting address 50, error -32
[Sun May  2 19:30:19 2021] usb 3-1-port1: unable to enumerate USB device
```

When the device successfully gets enumerated, it prints the Option Bytes and Internal Flash slots (I initially thought the eeprom could not retain the data on the board)

```
sudo dfu-util -l
dfu-util 0.10

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2020 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Deducing device DFU version from functional descriptor length
Found DFU: [0483:df11] ver=2200, devnum=57, cfg=1, intf=0, path="3-1.1", alt=1, name="@Option Bytes  /0x1FFFF800/01*016 e", serial="STM32"
Found DFU: [0483:df11] ver=2200, devnum=57, cfg=1, intf=0, path="3-1.1", alt=0, name="@Internal Flash  /0x08000000/128*002Kg", serial="STM32"
Found Runtime: [21ee:1100] ver=0391, devnum=9, cfg=1, intf=3, path="3-1.5.4.1", alt=0, name="UNKNOWN", serial="0009DD402B65"
```

Flashing using the verbose / -v option does not reveal anything interesting (to me at least)

```
sudo dfu-util -v -a 0 -D /data/amiga/flashfloppy-v3.23/FF_Gotek-v3.23.dfu
dfu-util 0.10

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2020 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

libusb version 1.0.23 (11397)
DFU suffix version 11a
Match vendor ID from file: 0483
Match product ID from file: df11
Deducing device DFU version from functional descriptor length
Opening DFU capable USB device...
ID 0483:df11
Run-time device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuERROR, status = 10
dfuERROR, clearing status
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 2048
DfuSe interface name: "Internal Flash  "
Memory segment at 0x08000000 128 x 2048 = 262144 (rew)
file contains 1 DFU images
Please note that the next version of dfu-util will automatically
set alternate interfaces based on the DfuSe file images!
parsing DFU image 1
Target name: ST...
image for alternate setting 0, (2 elements, total size = 112612)
parsing element 1, address = 0x08000000, size = 30328
Erasing page size 2048 at address 0x08000000, page starting at 0x08000000
Erasing page size 2048 at address 0x08000800, page starting at 0x08000800
Erasing page size 2048 at address 0x08001000, page starting at 0x08001000
Erasing page size 2048 at address 0x08001800, page starting at 0x08001800
Erasing page size 2048 at address 0x08002000, page starting at 0x08002000
Erasing page size 2048 at address 0x08002800, page starting at 0x08002800
Erasing page size 2048 at address 0x08003000, page starting at 0x08003000
Erasing page size 2048 at address 0x08003800, page starting at 0x08003800
Erasing page size 2048 at address 0x08004000, page starting at 0x08004000
Erasing page size 2048 at address 0x08004800, page starting at 0x08004800
Erasing page size 2048 at address 0x08005000, page starting at 0x08005000
Erasing page size 2048 at address 0x08005800, page starting at 0x08005800
Erasing page size 2048 at address 0x08006000, page starting at 0x08006000
Erasing page size 2048 at address 0x08006800, page starting at 0x08006800
Erasing page size 2048 at address 0x08007000, page starting at 0x08007000
 Download from image offset 00000000 to memory 08000000-080007ff, size 2048
 Download from image offset 00000800 to memory 08000800-08000fff, size 2048
 Download from image offset 00001000 to memory 08001000-080017ff, size 2048
 Download from image offset 00001800 to memory 08001800-08001fff, size 2048
 Download from image offset 00002000 to memory 08002000-080027ff, size 2048
 Download from image offset 00002800 to memory 08002800-08002fff, size 2048
 Download from image offset 00003000 to memory 08003000-080037ff, size 2048
 Download from image offset 00003800 to memory 08003800-08003fff, size 2048
 Download from image offset 00004000 to memory 08004000-080047ff, size 2048
 Download from image offset 00004800 to memory 08004800-08004fff, size 2048
 Download from image offset 00005000 to memory 08005000-080057ff, size 2048
 Download from image offset 00005800 to memory 08005800-08005fff, size 2048
 Download from image offset 00006000 to memory 08006000-080067ff, size 2048
 Download from image offset 00006800 to memory 08006800-08006fff, size 2048
 Download from image offset 00007000 to memory 08007000-08007677, size 1656
parsing element 2, address = 0x08008000, size = 82268
Erasing page size 2048 at address 0x08008000, page starting at 0x08008000
Erasing page size 2048 at address 0x08008800, page starting at 0x08008800
Erasing page size 2048 at address 0x08009000, page starting at 0x08009000
Erasing page size 2048 at address 0x08009800, page starting at 0x08009800
Erasing page size 2048 at address 0x0800a000, page starting at 0x0800a000
Erasing page size 2048 at address 0x0800a800, page starting at 0x0800a800
Erasing page size 2048 at address 0x0800b000, page starting at 0x0800b000
Erasing page size 2048 at address 0x0800b800, page starting at 0x0800b800
Erasing page size 2048 at address 0x0800c000, page starting at 0x0800c000
Erasing page size 2048 at address 0x0800c800, page starting at 0x0800c800
Erasing page size 2048 at address 0x0800d000, page starting at 0x0800d000
Erasing page size 2048 at address 0x0800d800, page starting at 0x0800d800
Erasing page size 2048 at address 0x0800e000, page starting at 0x0800e000
Erasing page size 2048 at address 0x0800e800, page starting at 0x0800e800
Erasing page size 2048 at address 0x0800f000, page starting at 0x0800f000
Erasing page size 2048 at address 0x0800f800, page starting at 0x0800f800
Erasing page size 2048 at address 0x08010000, page starting at 0x08010000
Erasing page size 2048 at address 0x08010800, page starting at 0x08010800
Erasing page size 2048 at address 0x08011000, page starting at 0x08011000
Erasing page size 2048 at address 0x08011800, page starting at 0x08011800
Erasing page size 2048 at address 0x08012000, page starting at 0x08012000
Erasing page size 2048 at address 0x08012800, page starting at 0x08012800
Erasing page size 2048 at address 0x08013000, page starting at 0x08013000
Erasing page size 2048 at address 0x08013800, page starting at 0x08013800
Erasing page size 2048 at address 0x08014000, page starting at 0x08014000
Erasing page size 2048 at address 0x08014800, page starting at 0x08014800
Erasing page size 2048 at address 0x08015000, page starting at 0x08015000
Erasing page size 2048 at address 0x08015800, page starting at 0x08015800
Erasing page size 2048 at address 0x08016000, page starting at 0x08016000
Erasing page size 2048 at address 0x08016800, page starting at 0x08016800
Erasing page size 2048 at address 0x08017000, page starting at 0x08017000
Erasing page size 2048 at address 0x08017800, page starting at 0x08017800
Erasing page size 2048 at address 0x08018000, page starting at 0x08018000
Erasing page size 2048 at address 0x08018800, page starting at 0x08018800
Erasing page size 2048 at address 0x08019000, page starting at 0x08019000
Erasing page size 2048 at address 0x08019800, page starting at 0x08019800
Erasing page size 2048 at address 0x0801a000, page starting at 0x0801a000
Erasing page size 2048 at address 0x0801a800, page starting at 0x0801a800
Erasing page size 2048 at address 0x0801b000, page starting at 0x0801b000
Erasing page size 2048 at address 0x0801b800, page starting at 0x0801b800
Erasing page size 2048 at address 0x0801c000, page starting at 0x0801c000
 Download from image offset 00000000 to memory 08008000-080087ff, size 2048
 Download from image offset 00000800 to memory 08008800-08008fff, size 2048
 Download from image offset 00001000 to memory 08009000-080097ff, size 2048
 Download from image offset 00001800 to memory 08009800-08009fff, size 2048
 Download from image offset 00002000 to memory 0800a000-0800a7ff, size 2048
 Download from image offset 00002800 to memory 0800a800-0800afff, size 2048
 Download from image offset 00003000 to memory 0800b000-0800b7ff, size 2048
 Download from image offset 00003800 to memory 0800b800-0800bfff, size 2048
 Download from image offset 00004000 to memory 0800c000-0800c7ff, size 2048
 Download from image offset 00004800 to memory 0800c800-0800cfff, size 2048
 Download from image offset 00005000 to memory 0800d000-0800d7ff, size 2048
 Download from image offset 00005800 to memory 0800d800-0800dfff, size 2048
 Download from image offset 00006000 to memory 0800e000-0800e7ff, size 2048
 Download from image offset 00006800 to memory 0800e800-0800efff, size 2048
 Download from image offset 00007000 to memory 0800f000-0800f7ff, size 2048
 Download from image offset 00007800 to memory 0800f800-0800ffff, size 2048
 Download from image offset 00008000 to memory 08010000-080107ff, size 2048
 Download from image offset 00008800 to memory 08010800-08010fff, size 2048
 Download from image offset 00009000 to memory 08011000-080117ff, size 2048
 Download from image offset 00009800 to memory 08011800-08011fff, size 2048
 Download from image offset 0000a000 to memory 08012000-080127ff, size 2048
 Download from image offset 0000a800 to memory 08012800-08012fff, size 2048
 Download from image offset 0000b000 to memory 08013000-080137ff, size 2048
 Download from image offset 0000b800 to memory 08013800-08013fff, size 2048
 Download from image offset 0000c000 to memory 08014000-080147ff, size 2048
 Download from image offset 0000c800 to memory 08014800-08014fff, size 2048
 Download from image offset 0000d000 to memory 08015000-080157ff, size 2048
 Download from image offset 0000d800 to memory 08015800-08015fff, size 2048
 Download from image offset 0000e000 to memory 08016000-080167ff, size 2048
 Download from image offset 0000e800 to memory 08016800-08016fff, size 2048
 Download from image offset 0000f000 to memory 08017000-080177ff, size 2048
 Download from image offset 0000f800 to memory 08017800-08017fff, size 2048
 Download from image offset 00010000 to memory 08018000-080187ff, size 2048
 Download from image offset 00010800 to memory 08018800-08018fff, size 2048
 Download from image offset 00011000 to memory 08019000-080197ff, size 2048
 Download from image offset 00011800 to memory 08019800-08019fff, size 2048
 Download from image offset 00012000 to memory 0801a000-0801a7ff, size 2048
 Download from image offset 00012800 to memory 0801a800-0801afff, size 2048
 Download from image offset 00013000 to memory 0801b000-0801b7ff, size 2048
 Download from image offset 00013800 to memory 0801b800-0801bfff, size 2048
 Download from image offset 00014000 to memory 0801c000-0801c15b, size 348
Done parsing DfuSe file
```

Same with listing the device with verbose info

```
sudo dfu-util -lv
dfu-util 0.10

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2020 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

libusb version 1.0.23 (11397)
Deducing device DFU version from functional descriptor length
Found DFU: [0483:df11] ver=2200, devnum=57, cfg=1, intf=0, path="3-1.1", alt=1, name="@Option Bytes  /0x1FFFF800/01*016 e", serial="STM32"
Found DFU: [0483:df11] ver=2200, devnum=57, cfg=1, intf=0, path="3-1.1", alt=0, name="@Internal Flash  /0x08000000/128*002Kg", serial="STM32"
Found Runtime: [21ee:1100] ver=0391, devnum=9, cfg=1, intf=3, path="3-1.5.4.1", alt=0, name="UNKNOWN", serial="0009DD402B65"
```

Similarly, deleting flash with verbose option set:

```
sudo dfu-util -v -a 0 -s :unprotect:force -D /data/amiga/flashfloppy-v3.23/FF_Gotek-v3.23.dfu
dfu-util 0.10

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2020 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

libusb version 1.0.23 (11397)
DFU suffix version 11a
Match vendor ID from file: 0483
Match product ID from file: df11
Deducing device DFU version from functional descriptor length
Opening DFU capable USB device...
ID 0483:df11
Run-time device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuERROR, status = 10
dfuERROR, clearing status
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 2048
DfuSe interface name: "Internal Flash  "
Memory segment at 0x08000000 128 x 2048 = 262144 (rew)
Device disconnects, erases flash and resets now
```

**Comment by keirf** [comment]
Perhaps if this is a new Gotek it has the AT32F415 chip? You need to use Artery DFU tool to program, and use latest firmware (v3.25). See the wiki: https://github.com/keirf/FlashFloppy/wiki/Gotek-Compatibility#update-april-2021-artery-microcontrollers

**Comment by Drag0nFly** [comment]
I thought the same before opening the ticket based on https://github.com/keirf/FlashFloppy/issues/453 + https://github.com/keirf/FlashFloppy/issues/453

But it is the STM32 chip w/ 128k RAM-

```
Found DFU: [0483:df11] ver=2200, devnum=59, cfg=1, intf=0, path="3-1.1", alt=1, name="@Option Bytes  /0x1FFFF800/01*016 e", serial="STM32"
Found DFU: [0483:df11] ver=2200, devnum=59, cfg=1, intf=0, path="3-1.1", alt=0, name="@Internal Flash  /0x08000000/128*002Kg", serial="STM32"
```

The USB device listing identifies it as “STMicroelectronics STM Device in DFU Mode” (should be different if it's the AT chip)

Since this is my first attempt at flashing using dfu-util, I assumed it was something trivial. I looked for a “verify” option in the tool, but it appears that such an option does not exist (in order to verify what is on the board against the actual .dfu file)

**Comment by Drag0nFly** [comment]
Did some more testing with this Gotek board, including flashing it again a number of times. I also compared with a different Gotek drive, running on older 0.9.16a firmware. The latter works fine (probably a coincidence).

However, it might be useful to attempt running it with the exact same FF version.

Still, it probably would not explain why the LED does not light up at all, and that USB activity is not registered. The only activity, assuming the jumper is correctly set to S0, is the blinking green led on the Gotek during Amiga bootup. Plugging in a USB drive does not change anything, nor does pressing the buttons.

This is a longshot I know, but as I see the 0.9.16a version is available I thought I'd be an idea to try it as well. Obviously it is missing a .dfu file – is there a way to process the .upd & .hex file into a .dfu in order to test this? If not I can probably revert to the "old way" of flashing providing this would work within a virtual machine.

Naturally, if there any other thoughts as to what might be going on with this board those would be appreciated as well. (I'm not ready yet to throw it away since it is my last spare Gotek drive...)

**Comment by keirf** [comment]
There is a script in `scripts/dfu-convert.py` which can be used:
```
$(PYTHON) ./scripts/dfu-convert.py -i FF.hex FF.dfu
```

**Comment by Drag0nFly** [comment]
Ok, I found it (or a version of it) after looking around a bit (github's search didn't turn anything up)

However, it appears to have been last updated 11 years ago. There were some syntax issues for print statements - which I corrected, but it currently bombs out with:

```
python ../dfu-convert.py -i FF_Gotek-v0.9.16a.hex FF_Gotek-v0.9.16a.dfu
Traceback (most recent call last):
  File "/data/amiga/flashfloppy_v0.9.16a/../dfu-convert.py", line 57, in <module>
    build(outfile,[target],device)
  File "/data/amiga/flashfloppy_v0.9.16a/../dfu-convert.py", line 19, in build
    tdata += struct.pack('<2I',image['address'],len(image['data']))+image['data']
TypeError: can only concatenate str (not "bytes") to str
```

Is this working on newer distros / python versions? (tried both python3 &2)

**Comment by Drag0nFly** [comment]
Strike that. Missing some deps for a correctly-working python2 – sorry for the noise.

**Comment by keirf** [comment]
It's included in the FlashFloppy github repository. It's the script I use to generate the release DFUs.

**Comment by Drag0nFly** [comment]
Yes, it's just GitHub's search function which proved a little lacking...

We couldn’t find any code matching 'dfu-convert.py' in keirf/FlashFloppy
You could search all of GitHub or try an advanced search.

**Comment by Drag0nFly** [comment]
Same behaviour with 0.9.16a (anything else would frankly have been even stranger). Leaves the question whether anything is actually being written to the Gotek, as it exhibits the exact same behaviour it had when it was unflashed from the factory.

Will the LED register when hooked up to an Amiga for such boards (i.e, unflashed from factory)? If so it must be a harddware issue.

The only difference is that the previous Goteks I flashed were done using the “DfuSe_Demo v3.0.5” tool. (However, running that successfully in a VM – or wrangling with a M$ OS in itself – has proved to be an introduction to modern mental torture techniques...)
